definitions:
  models.Images:
    properties:
      title:
        example: Спуск. Фото №99
        type: string
      url:
        example: http://...
        type: string
    type: object
  models.Pereval:
    properties:
      add_time:
        example: "2021-09-22 13:18:13"
        type: string
      beautyTitle:
        example: 'пер. '
        type: string
      connect:
        example: ' '
        type: string
      coords:
        properties:
          height:
            example: "1200"
            type: string
          latitude:
            example: "45.3842"
            type: string
          longitude:
            example: "7.1525"
            type: string
        type: object
      images:
        items:
          $ref: '#/definitions/models.Images'
        type: array
      level:
        properties:
          autumn:
            example: 1A
            type: string
          spring:
            example: ' '
            type: string
          summer:
            example: 1A
            type: string
          winter:
            example: ' '
            type: string
        type: object
      other_titles:
        example: "1"
        type: string
      pereval_id:
        example: "125"
        type: string
      title:
        example: Туя-Ашуу
        type: string
      type:
        example: pass
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.Response:
    description: 'Структура HTTP ответа: если отправка успешна, дополнительно возвращается
      id вставленной записи.'
    properties:
      id:
        example: "123"
        type: string
      message:
        example: OK
        type: string
    type: object
  models.ResponseErr:
    description: Структура HTTP ответа об ошибке
    properties:
      message:
        example: 'ошибка: описание ошибки'
        type: string
    type: object
  models.User:
    properties:
      email:
        example: dd@aa.ru
        type: string
      fam:
        example: Скворцов
        type: string
      id:
        example: "11234"
        type: string
      name:
        example: Иван
        type: string
      otc:
        example: Кожедубович
        type: string
      phone:
        example: "+744434555"
        type: string
    type: object
info:
  contact:
    email: serj_bibox@mail.ru
    name: API Support
  description: API для взаимодействия приложения с сервером БД ФСТР.
  title: ФСТР API
  version: "1.0"
paths:
  /submitData:
    post:
      consumes:
      - application/json
      parameters:
      - description: карточка объекта
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Pereval'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseErr'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseErr'
      summary: Создаёт новую запись в pereval_added
      tags:
      - /submitData
swagger: "2.0"
