definitions:
  apis.ErrResponse:
    description: Структура HTTP ответа ERROR
    properties:
      error:
        type: string
    type: object
  apis.InsertResponse:
    description: Структура HTTP ответа метода POST /submitData
    properties:
      id:
        example: "123"
        type: string
      message:
        example: OK
        type: string
    type: object
  apis.PassArrayResponse:
    description: Структура HTTP ответа метода PUT /submitData/{id}
    properties:
      parray:
        items:
          $ref: '#/definitions/models.PassLoaded'
        type: array
    type: object
  apis.PassResponse:
    description: Структура HTTP ответа метода GET /submitData/{id}
    properties:
      passLoaded:
        $ref: '#/definitions/models.PassLoaded'
    type: object
  apis.QueryParam:
    description: 'Структура тела запроса метода GET /submitData Необходимые поля:
      Phone | Email | Fam & Name & OTC'
    properties:
      email:
        example: sample@sample.com
        type: string
      fam:
        example: Иванов
        type: string
      name:
        example: Иван
        type: string
      otc:
        example: Иванович
        type: string
      phone:
        example: "+71234567890"
        type: string
    type: object
  apis.StatusResponse:
    description: Структура HTTP ответа метода GET /submitData/{id}/status
    properties:
      id:
        example: "123"
        type: string
      status:
        example: new
        type: string
    type: object
  models.ImageLoaded:
    properties:
      blob:
        description: Строку удобнее тестировать
        type: string
      title:
        example: Спуск. Фото №99
        type: string
    type: object
  models.Images:
    properties:
      title:
        example: Спуск. Фото №99
        type: string
      url:
        example: https://img.icons8.com/ios/2x/roller-skating.png
        type: string
    type: object
  models.Pass:
    description: Структура тела запроса POST /submitData
    properties:
      add_time:
        example: "2021-09-22 13:18:13"
        type: string
      beautyTitle:
        example: 'пер. '
        type: string
      connect:
        example: ' '
        type: string
      coords:
        properties:
          height:
            example: "1200"
            type: string
          latitude:
            example: "45.3842"
            type: string
          longitude:
            example: "7.1525"
            type: string
        type: object
      images:
        items:
          $ref: '#/definitions/models.Images'
        type: array
      level:
        properties:
          autumn:
            example: 1A
            type: string
          spring:
            example: ' '
            type: string
          summer:
            example: 1A
            type: string
          winter:
            example: ' '
            type: string
        type: object
      other_titles:
        example: "1"
        type: string
      pereval_id:
        example: "125"
        type: string
      title:
        example: Туя-Ашуу
        type: string
      type:
        example: pass
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.PassLoaded:
    description: Структура поля raw_data таблицы pereval_added
    properties:
      add_time:
        example: "2021-09-22 13:18:13"
        type: string
      beautyTitle:
        example: 'пер. '
        type: string
      connect:
        example: ' '
        type: string
      coords:
        properties:
          height:
            example: "1200"
            type: string
          latitude:
            example: "45.3842"
            type: string
          longitude:
            example: "7.1525"
            type: string
        type: object
      images:
        items:
          $ref: '#/definitions/models.ImageLoaded'
        type: array
      level:
        properties:
          autumn:
            example: 1A
            type: string
          spring:
            example: ' '
            type: string
          summer:
            example: 1A
            type: string
          winter:
            example: ' '
            type: string
        type: object
      other_titles:
        example: "1"
        type: string
      pereval_id:
        example: "125"
        type: string
      title:
        example: Туя-Ашуу
        type: string
      type:
        example: pass
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.User:
    properties:
      email:
        example: dd@aa.ru
        type: string
      fam:
        example: Скворцов
        type: string
      id:
        example: "11234"
        type: string
      name:
        example: Иван
        type: string
      otc:
        example: Кожедубович
        type: string
      phone:
        example: "+744434555"
        type: string
    type: object
info:
  contact:
    email: serj_bibox@mail.ru
    name: API Support
  description: API для взаимодействия приложения с сервером БД ФСТР.
  title: ФСТР API
  version: "1.0"
paths:
  /submitData:
    post:
      consumes:
      - application/json
      parameters:
      - description: карточка объекта
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Pass'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.InsertResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apis.ErrResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/apis.ErrResponse'
      summary: Создаёт новую запись в pereval_added
      tags:
      - /submitData
  /submitData/:
    get:
      consumes:
      - application/json
      description: К сожалению, Swagger считает, что у GET запроса не должно быть
        тела. Можно проверить этот запрос, например, в Postman.
      parameters:
      - description: Фильтровать по email
        format: email
        in: body
        name: email
        schema:
          $ref: '#/definitions/apis.QueryParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.PassArrayResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apis.ErrResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/apis.ErrResponse'
      summary: список всех данных для отображения, которые этот пользователь отправил
        на сервер через приложение с возможностью фильтрации по данным пользователя
        (ФИО, телефон, почта), если передан объект.
      tags:
      - /submitData/
  /submitData/{id}:
    get:
      parameters:
      - description: pereval_added PRIMARY KEY ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.PassResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apis.ErrResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/apis.ErrResponse'
      summary: Получает запись из pereval_added по ID записи
      tags:
      - /submitData/{id}
    put:
      consumes:
      - application/json
      parameters:
      - description: pereval_added PRIMARY KEY ID
        in: path
        name: id
        required: true
        type: integer
      - description: карточка объекта
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Pass'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.InsertResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apis.ErrResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/apis.ErrResponse'
      summary: Редактирует существующую запись в pereval_added , если она в статусе
        "new"
      tags:
      - /submitData/{id}
  /submitData/{id}/status:
    get:
      parameters:
      - description: pereval_added PRIMARY KEY ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apis.ErrResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/apis.ErrResponse'
      summary: Получает записи из pereval_added по ID записи
      tags:
      - /submitData/{id}/status
swagger: "2.0"
